#ifndef __EVENT_H
#define __EVENT_H

#include <SDL2/SDL.h>

#include "point2D.h"


enum EventType {
    /*EVENT_AUDIODEVICEADDED = SDL_AUDIODEVICEADDED,
    EVENT_AUDIODEVICEREMOVED = SDL_AUDIODEVICEREMOVED,
    EVENT_CONTROLLERAXISMOTION = SDL_CONTROLLERAXISMOTION,
    EVENT_CONTROLLERBUTTONDOWN = SDL_CONTROLLERBUTTONDOWN,
    EVENT_CONTROLLERBUTTONUP = SDL_CONTROLLERBUTTONUP,
    EVENT_CONTROLLERDEVICEADDED = SDL_CONTROLLERDEVICEADDED,
    EVENT_CONTROLLERDEVICEREMOVED = SDL_CONTROLLERDEVICEREMOVED,
    EVENT_CONTROLLERDEVICEREMAPPED = SDL_CONTROLLERDEVICEREMAPPED,
    EVENT_DOLLARGESTURE = SDL_DOLLARGESTURE,
    EVENT_DOLLARRECORD = SDL_DOLLARRECORD,
    EVENT_DROPFILE = SDL_DROPFILE,
    EVENT_DROPTEXT = SDL_DROPTEXT,
    EVENT_DROPBEGIN = SDL_DROPBEGIN,
    EVENT_DROPCOMPLETE = SDL_DROPCOMPLETE,
    EVENT_FINGERMOTION = SDL_FINGERMOTION,
    EVENT_FINGERDOWN = SDL_FINGERDOWN,
    EVENT_FINGERUP = SDL_FINGERUP,
    EVENT_KEYDOWN = SDL_KEYDOWN,
    EVENT_KEYUP = SDL_KEYUP,
    EVENT_JOYAXISMOTION = SDL_JOYAXISMOTION,
    EVENT_JOYBALLMOTION = SDL_JOYBALLMOTION,
    EVENT_JOYHATMOTION = SDL_JOYHATMOTION,
    EVENT_JOYBUTTONDOWN = SDL_JOYBUTTONDOWN,
    EVENT_JOYBUTTONUP = SDL_JOYBUTTONUP,
    EVENT_JOYDEVICEADDED = SDL_JOYDEVICEADDED,
    EVENT_JOYDEVICEREMOVED = SDL_JOYDEVICEREMOVED,*/
    EVENT_MOUSEMOTION = SDL_MOUSEMOTION,
    EVENT_MOUSEBUTTONDOWN = SDL_MOUSEBUTTONDOWN,
    EVENT_MOUSEBUTTONUP = SDL_MOUSEBUTTONUP,
    //EVENT_MOUSEWHEEL = SDL_MOUSEWHEEL,
    //EVENT_MULTIGESTURE = SDL_MULTIGESTURE,
    EVENT_QUIT = SDL_QUIT/*,
    EVENT_SYSWMEVENT = SDL_SYSWMEVENT,
    EVENT_TEXTEDITING = SDL_TEXTEDITING,
    EVENT_TEXTINPUT = SDL_TEXTINPUT,
    EVENT_USEREVENT = SDL_USEREVENT,
    EVENT_WINDOWEVENT = SDL_WINDOWEVENT*/
};

class Event {

public:

    void poll();
    EventType getType();

    void setPoint2D(Point2D& p);
private:

    SDL_Event event;

};

#endif /* __EVENT_H */
